# Generated by Django 3.0.5 on 2020-05-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200518_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='complete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actioncomplete', models.CharField(max_length=100)),
                ('date_completed', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
